name: "MasterPlugin"
version: "0.1.1"
main: "com.masterplugin.Main"
author: "Domingo Álvarez"
description: "This plugin does so much stuff it can't be contained!"
api-version: "1.8.8"
commands:
  change:
    usage0: "name color [color] [player_name?]"
    usage1: "prefix color [color] [player_name?]"
    usage2: "player rank [player_name]"
  list:
    usage0: "colors"
    usage1: "commands"
    usage1: "warps"
  add:
    usage0: "rank [rank_name]"
    usage1: "rank permission [rank_name] [permission_name]"
    usage2: "chat player [chat_name] [player_name]"
  delete:
    usage0: "rank permission [rank_name] [permission_name]"
    usage1: "chat player [chat_name] [player_name]"
    usage2: "chat [chat_name]"
  chunksLoaded:
  warp:
    usage0: "[warp_name]"
  ping:
    usage0: "[player_name?]"
  tpRandom:
    usage0: "[player_name?]"
  create:
    usage0: "warp [warp_name]"
  delete:
    usage0: "warp [warp_name]"
  warp:
    usage0: "[warp_name]"
  seen:
    usage0: "[player_name?]"
  ping:
    usage0: "[player_name?]"